import type { Bot } from './data';

export const voltaBots: Bot[] = [
  {
    slug: 'reonic-sync',
    name: 'Aurora Solar Sync',
    cat: 'CRM',
    desc: 'Syncs projects, contacts, and quotes from Aurora Solar CRM into the .birdie database',
    state: 'success',
    pill: 'LIVE',
    runs: '184',
    conns: 'Aurora Solar API · Supabase',
    version: 'v2.1',
    schedule: 'Daily 03:00',
    trigger: 'Cron · 0 3 * * *',
    successRate: '99.4%',
    avgDuration: '18.6s',
    lastRun: '6 hrs ago',
    activity24h: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'AURORA_API_KEY', value: '•••••••• (vault)' },
      { key: 'AURORA_BASE_URL', value: 'https://api.aurorasolar.com/v2' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
      { key: 'SUPABASE_SERVICE_KEY', value: '•••••••• (vault)' },
    ],
    recentRuns: [
      { time: '03:00', duration: '17.8s', state: 'success', output: '42 projects · 18 contacts · 7 quotes synced' },
      { time: '03:00', duration: '19.2s', state: 'success', output: '38 projects · 12 contacts · 5 quotes synced' },
      { time: '03:00', duration: '16.4s', state: 'success', output: '41 projects · 15 contacts · 9 quotes synced' },
      { time: '03:00', duration: '22.1s', state: 'warning', output: 'Aurora Solar rate limit 429 · Retry successful' },
      { time: '03:00', duration: '18.9s', state: 'success', output: '39 projects · 20 contacts · 4 quotes synced' },
    ],
    logs: [
      { ts: '03:00:01.112', level: 'INFO', msg: 'Trigger fired · run_id=rs_7k2m1a' },
      { ts: '03:00:01.245', level: 'INFO', msg: 'Aurora Solar API · GET /projects?updated_since=2026-06-06' },
      { ts: '03:00:04.812', level: 'INFO', msg: '→ 42 projects fetched' },
      { ts: '03:00:04.901', level: 'INFO', msg: 'Aurora Solar API · GET /contacts?updated_since=2026-06-06' },
      { ts: '03:00:06.412', level: 'INFO', msg: '→ 18 contacts fetched' },
      { ts: '03:00:06.512', level: 'INFO', msg: 'Aurora Solar API · GET /offers?updated_since=2026-06-06' },
      { ts: '03:00:08.112', level: 'INFO', msg: '→ 7 quotes fetched' },
      { ts: '03:00:08.245', level: 'INFO', msg: 'Supabase upsert · projects (42 rows)' },
      { ts: '03:00:12.812', level: 'INFO', msg: 'Supabase upsert · contacts (18 rows)' },
      { ts: '03:00:16.412', level: 'INFO', msg: 'Supabase upsert · offers (7 rows)' },
      { ts: '03:00:18.912', level: 'SUCCESS', msg: 'Run complete · 67 records synced · 0 errors' },
    ],
  },
  {
    slug: 'netzanmeldungs-bot',
    name: 'Interconnection Bot',
    cat: 'PRJ',
    desc: 'Automated portal submissions to utilities (PG&E, Oncor, Duke Energy, etc.) via Playwright',
    state: 'success',
    pill: 'LIVE',
    runs: '12',
    conns: 'Playwright · VPS 217.160.67.197',
    version: 'v3.4',
    schedule: 'Webhook · on demand',
    trigger: 'API call / manual',
    successRate: '94.2%',
    avgDuration: '48.3s',
    lastRun: '2 hrs ago',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'VPS_HOST', value: '217.160.67.197:3099' },
      { key: 'PORTAL_CREDENTIALS', value: '•••••••• (vault)' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
      { key: 'DRIVER_COUNT', value: '50 portal drivers' },
      { key: 'HEADLESS', value: 'true' },
    ],
    recentRuns: [
      { time: '09:14', duration: '52.1s', state: 'success', output: 'Oncor · Interconnection for project #P-4821 submitted' },
      { time: '08:47', duration: '44.8s', state: 'success', output: 'PG&E · Interconnection for project #P-4819 submitted' },
      { time: '08:22', duration: '38.2s', state: 'success', output: 'Oncor · Interconnection for project #P-4817 submitted' },
      { time: '07:58', duration: '62.4s', state: 'warning', output: 'Duke Energy · Captcha retry · Interconnection OK on 2nd attempt' },
      { time: '07:31', duration: '41.6s', state: 'success', output: 'PG&E · Interconnection for project #P-4815 submitted' },
    ],
    logs: [
      { ts: '09:14:01.012', level: 'INFO', msg: 'API trigger · project_id=P-4821 · utility=Oncor' },
      { ts: '09:14:01.245', level: 'INFO', msg: 'Loading driver: oncor-v2' },
      { ts: '09:14:02.812', level: 'INFO', msg: 'Playwright · launching headless browser' },
      { ts: '09:14:04.412', level: 'INFO', msg: 'Login Oncor Portal · oncor.interconnect.com' },
      { ts: '09:14:12.612', level: 'INFO', msg: 'Navigating to interconnection · Form step 1/4' },
      { ts: '09:14:28.812', level: 'INFO', msg: 'Filling PDF data · 18 fields populated' },
      { ts: '09:14:42.112', level: 'INFO', msg: 'Upload: site plan + wiring diagram + data sheet' },
      { ts: '09:14:48.612', level: 'INFO', msg: 'Submit · Confirmation number: IC-2026-08412' },
      { ts: '09:14:52.112', level: 'SUCCESS', msg: 'Interconnection submitted · Screenshot saved · Supabase updated' },
    ],
  },
  {
    slug: 'email-sync',
    name: 'Email Sync',
    cat: 'COM',
    desc: 'IMAP sync of Google Workspace mailboxes (interconnection@sunpeak, info@sunpeak) — assigns emails to projects',
    state: 'success',
    pill: 'LIVE',
    runs: '96',
    conns: 'Google Workspace · n8n Cloud',
    version: 'v1.5',
    schedule: 'Every 15 minutes',
    trigger: 'Cron · */15 * * * *',
    successRate: '99.8%',
    avgDuration: '3.4s',
    lastRun: '8 min ago',
    activity24h: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
    envVars: [
      { key: 'IMAP_HOST', value: 'imap.gmail.com' },
      { key: 'IMAP_USER_NA', value: 'interconnection@sunpeak.solar' },
      { key: 'IMAP_USER_INFO', value: 'info@sunpeak.solar' },
      { key: 'IMAP_PASSWORD', value: '•••••••• (vault)' },
      { key: 'N8N_INSTANCE', value: 'voltasolaranlagen.app.n8n.cloud' },
    ],
    recentRuns: [
      { time: '10:45', duration: '3.2s', state: 'success', output: '4 new emails · 3 assigned to projects' },
      { time: '10:30', duration: '2.8s', state: 'success', output: '2 new emails · 2 assigned to projects' },
      { time: '10:15', duration: '3.1s', state: 'success', output: '6 new emails · 4 assigned to projects' },
      { time: '10:00', duration: '2.9s', state: 'success', output: '1 new email · assigned to project' },
      { time: '09:45', duration: '4.1s', state: 'warning', output: '8 emails · 2 without project match → Inbox' },
      { time: '09:30', duration: '3.0s', state: 'success', output: '3 new emails · 3 assigned to projects' },
    ],
    logs: [
      { ts: '10:45:01.112', level: 'INFO', msg: 'n8n trigger · workflow: Email-Sync-Volta' },
      { ts: '10:45:01.312', level: 'INFO', msg: 'IMAP connect · interconnection@sunpeak.solar' },
      { ts: '10:45:01.812', level: 'INFO', msg: '→ 2 new messages' },
      { ts: '10:45:02.012', level: 'INFO', msg: 'IMAP connect · info@sunpeak.solar' },
      { ts: '10:45:02.412', level: 'INFO', msg: '→ 2 new messages' },
      { ts: '10:45:02.812', level: 'INFO', msg: 'Matching to projects via sender/subject' },
      { ts: '10:45:03.812', level: 'INFO', msg: 'Supabase · 4 emails stored · 3 project_ids matched' },
      { ts: '10:45:04.312', level: 'SUCCESS', msg: 'Run complete · 4 emails processed' },
    ],
  },
  {
    slug: 'mahnbot',
    name: 'Dunning Bot',
    cat: 'FIN',
    desc: 'Automated payment reminders based on QuickBooks invoice status via n8n',
    state: 'success',
    pill: 'LIVE',
    runs: '4',
    conns: 'QuickBooks · Gmail SMTP · n8n',
    version: 'v2.1',
    schedule: 'Every 6 hours',
    trigger: 'Cron · 0 */6 * * *',
    successRate: '99.2%',
    avgDuration: '5.8s',
    lastRun: '22 min ago',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
    envVars: [
      { key: 'QUICKBOOKS_API_KEY', value: '•••••••• (vault)' },
      { key: 'SMTP_HOST', value: 'smtp.gmail.com' },
      { key: 'SMTP_USER', value: 'billing@sunpeak.solar' },
      { key: 'SMTP_PASSWORD', value: '•••••••• (vault)' },
      { key: 'DUNNING_FEE_1', value: '$ 5' },
      { key: 'DUNNING_FEE_2', value: '$ 15' },
      { key: 'N8N_INSTANCE', value: 'voltasolaranlagen.app.n8n.cloud' },
    ],
    recentRuns: [
      { time: '10:00', duration: '5.4s', state: 'success', output: '2 reminders sent · 0 errors' },
      { time: '04:00', duration: '4.9s', state: 'success', output: '0 reminders · no overdue items' },
      { time: '22:00', duration: '6.1s', state: 'success', output: '1 reminder sent · 0 errors' },
      { time: '16:00', duration: '5.8s', state: 'success', output: '3 reminders sent · 0 errors' },
      { time: '10:00', duration: '7.2s', state: 'warning', output: 'QuickBooks timeout · Retry successful' },
      { time: '04:00', duration: '5.1s', state: 'success', output: '0 reminders · no overdue items' },
    ],
    logs: [
      { ts: '10:00:01.231', level: 'INFO', msg: 'n8n trigger · workflow: Dunning-Bot-Volta' },
      { ts: '10:00:01.412', level: 'INFO', msg: 'QuickBooks API · GET /Invoice?status=200&overdue=true' },
      { ts: '10:00:02.892', level: 'INFO', msg: '→ 8 open invoices fetched' },
      { ts: '10:00:02.945', level: 'INFO', msg: 'Filtering: overdue > 7 days' },
      { ts: '10:00:03.012', level: 'INFO', msg: '→ 2 invoices overdue (level 1)' },
      { ts: '10:00:03.245', level: 'INFO', msg: 'Rendering dunning templates · brand=volta' },
      { ts: '10:00:04.412', level: 'INFO', msg: 'Gmail SMTP · sending 2 emails via billing@sunpeak.solar' },
      { ts: '10:00:05.812', level: 'INFO', msg: 'QuickBooks PATCH · Dunning status updated' },
      { ts: '10:00:06.412', level: 'SUCCESS', msg: 'Run complete · 2 dunning notices sent · 0 errors' },
    ],
  },
  {
    slug: 'lieferbestaetigung',
    name: 'Delivery Confirmation',
    cat: 'PRJ',
    desc: 'Automated confirmation emails to customers on delivery date updates from Aurora Solar',
    state: 'success',
    pill: 'LIVE',
    runs: '6',
    conns: 'Aurora Solar · Gmail SMTP · n8n',
    version: 'v1.2',
    schedule: 'Webhook',
    trigger: 'Aurora Solar delivery_date_set',
    successRate: '100%',
    avgDuration: '2.8s',
    lastRun: '45 min ago',
    activity24h: [0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'AURORA_WEBHOOK_SECRET', value: '•••••••• (vault)' },
      { key: 'SMTP_HOST', value: 'smtp.gmail.com' },
      { key: 'SMTP_USER', value: 'info@sunpeak.solar' },
      { key: 'SMTP_PASSWORD', value: '•••••••• (vault)' },
      { key: 'N8N_INSTANCE', value: 'voltasolaranlagen.app.n8n.cloud' },
    ],
    recentRuns: [
      { time: '09:48', duration: '2.6s', state: 'success', output: 'Confirmation to Johnson family · Delivery 06/12' },
      { time: '09:22', duration: '2.9s', state: 'success', output: 'Confirmation to Mr. Davis · Delivery 06/11' },
      { time: '08:55', duration: '3.1s', state: 'success', output: 'Confirmation to Martinez family · Delivery 06/13' },
      { time: '08:14', duration: '2.7s', state: 'success', output: 'Confirmation to Thompson Solar LLC · Delivery 06/10' },
    ],
    logs: [
      { ts: '09:48:01.112', level: 'INFO', msg: 'n8n webhook · Aurora Solar delivery_date_set · project=P-4832' },
      { ts: '09:48:01.345', level: 'INFO', msg: 'Loading customer data · Johnson family' },
      { ts: '09:48:01.812', level: 'INFO', msg: 'Rendering template: delivery_confirmation_v2' },
      { ts: '09:48:02.412', level: 'INFO', msg: 'Gmail SMTP · sending to johnson@example.com' },
      { ts: '09:48:03.712', level: 'SUCCESS', msg: 'Confirmation sent · Delivery date 06/12/2026' },
    ],
  },
  {
    slug: 'ki-dokumenten-filler',
    name: 'AI Document Filler',
    cat: 'PRJ',
    desc: 'Auto-fills interconnection PDFs using Claude Haiku AI — 100+ templates, 25 utilities',
    state: 'success',
    pill: 'LIVE',
    runs: '18',
    conns: 'Claude Haiku · Supabase · PDF Engine',
    version: 'v2.8',
    schedule: 'On demand',
    trigger: 'API call from Interconnection Bot',
    successRate: '97.8%',
    avgDuration: '6.2s',
    lastRun: '2 hrs ago',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 3, 4, 5, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'ANTHROPIC_API_KEY', value: '•••••••• (vault)' },
      { key: 'AI_MODEL', value: 'claude-haiku' },
      { key: 'TEMPLATE_COUNT', value: '108' },
      { key: 'UTILITY_COUNT', value: '25' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
    ],
    recentRuns: [
      { time: '09:12', duration: '5.8s', state: 'success', output: 'PDF filled · Oncor system registration · 24 fields' },
      { time: '08:48', duration: '6.4s', state: 'success', output: 'PDF filled · PG&E net metering application · 31 fields' },
      { time: '08:22', duration: '7.1s', state: 'warning', output: 'PDF filled · 2 fields uncertain (confidence < 80%)' },
      { time: '07:58', duration: '5.9s', state: 'success', output: 'PDF filled · Duke Energy commissioning · 19 fields' },
      { time: '07:31', duration: '6.2s', state: 'success', output: 'PDF filled · PG&E system registration · 28 fields' },
    ],
    logs: [
      { ts: '09:12:01.012', level: 'INFO', msg: 'API call · fill_pdf · template=oncor_interconnection_app_v3' },
      { ts: '09:12:01.245', level: 'INFO', msg: 'Loading project data · P-4821 from Supabase' },
      { ts: '09:12:01.812', level: 'INFO', msg: 'Claude Haiku · extracting field values from project context' },
      { ts: '09:12:04.012', level: 'INFO', msg: '→ 24/24 fields mapped · confidence avg 94%' },
      { ts: '09:12:04.412', level: 'INFO', msg: 'PDF Engine · filling template · oncor_interconnection_app_v3.pdf' },
      { ts: '09:12:06.012', level: 'INFO', msg: 'Supabase storage · upload filled PDF' },
      { ts: '09:12:06.812', level: 'SUCCESS', msg: 'PDF complete · 24 fields · 0 warnings' },
    ],
  },
  {
    slug: 'enrichment-bot',
    name: 'Enrichment Bot',
    cat: 'CRM',
    desc: 'Extracts technical data from Aurora Solar documents (kW DC, inverter type, storage) via AI',
    state: 'success',
    pill: 'LIVE',
    runs: '34',
    conns: 'Claude Haiku · Aurora Solar · Supabase',
    version: 'v1.6',
    schedule: 'Every 2 hours',
    trigger: 'Cron · 0 */2 * * *',
    successRate: '96.4%',
    avgDuration: '12.4s',
    lastRun: '38 min ago',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    envVars: [
      { key: 'ANTHROPIC_API_KEY', value: '•••••••• (vault)' },
      { key: 'AI_MODEL', value: 'claude-haiku' },
      { key: 'AURORA_API_KEY', value: '•••••••• (vault)' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
      { key: 'EXTRACT_FIELDS', value: 'kw_dc,inverter_type,storage_kwh,module_count' },
    ],
    recentRuns: [
      { time: '10:00', duration: '11.8s', state: 'success', output: '5 documents enriched · 18 fields extracted' },
      { time: '08:00', duration: '14.2s', state: 'success', output: '8 documents enriched · 29 fields extracted' },
      { time: '06:00', duration: '9.8s', state: 'success', output: '3 documents enriched · 11 fields extracted' },
      { time: '04:00', duration: '12.1s', state: 'warning', output: '6 documents · 1 PDF unreadable (scan quality)' },
      { time: '02:00', duration: '13.4s', state: 'success', output: '7 documents enriched · 24 fields extracted' },
    ],
    logs: [
      { ts: '10:00:01.112', level: 'INFO', msg: 'Trigger fired · run_id=eb_3f8k2c' },
      { ts: '10:00:01.345', level: 'INFO', msg: 'Aurora Solar API · fetching unprocessed documents' },
      { ts: '10:00:02.812', level: 'INFO', msg: '→ 5 new documents since last run' },
      { ts: '10:00:03.012', level: 'INFO', msg: 'Claude Haiku · extracting: kW DC, inverter type, storage, module count' },
      { ts: '10:00:08.412', level: 'INFO', msg: '→ Doc 1: 9.8 kW DC · Fronius GEN24 · BYD HVS 10.2 · 24 modules' },
      { ts: '10:00:09.812', level: 'INFO', msg: '→ Doc 2: 12.4 kW DC · SMA STP · no battery · 31 modules' },
      { ts: '10:00:11.012', level: 'INFO', msg: 'Supabase · updating project_technical_data (5 rows)' },
      { ts: '10:00:12.912', level: 'SUCCESS', msg: 'Run complete · 5 docs · 18 fields extracted · 0 errors' },
    ],
  },
  {
    slug: 'ecoflow-connector',
    name: 'EcoFlow Connector',
    cat: 'IOT',
    desc: 'Monitoring of customer systems via EcoFlow IoT API — devices still need to be linked',
    state: 'neutral',
    pill: 'SETUP',
    runs: '—',
    conns: 'EcoFlow IoT API · Supabase',
    version: 'v0.3',
    schedule: 'Every 5 minutes (planned)',
    trigger: 'Cron · */5 * * * * (inactive)',
    successRate: '—',
    avgDuration: '—',
    lastRun: 'never',
    activity24h: Array(24).fill(0),
    envVars: [
      { key: 'ECOFLOW_ACCESS_KEY', value: '•••••••• (vault)' },
      { key: 'ECOFLOW_SECRET_KEY', value: '•••••••• (vault)' },
      { key: 'ECOFLOW_API_URL', value: 'https://api.ecoflow.com/iot-open' },
      { key: 'DEVICES_LINKED', value: '0 / 12 planned' },
    ],
    recentRuns: [],
    logs: [
      { ts: '—', level: 'WARN', msg: 'Bot waiting for device linking · EcoFlow customer devices need to be linked in the portal' },
      { ts: '—', level: 'INFO', msg: 'API access tested · Auth OK · 0 devices linked' },
    ],
  },
];

export function getVoltaBot(slug: string): Bot | undefined {
  return voltaBots.find((b) => b.slug === slug);
}
