import type { Bot } from './data';

export const voltaBots: Bot[] = [
  {
    slug: 'reonic-sync',
    name: 'Reonic-Sync',
    cat: 'CRM',
    desc: 'Synchronisiert Projekte, Kontakte und Angebote aus Reonic CRM in die .birdie-Datenbank',
    state: 'success',
    pill: 'LIVE',
    runs: '184',
    conns: 'Reonic v3 API · Supabase',
    version: 'v2.1',
    schedule: 'Täglich 03:00',
    trigger: 'Cron · 0 3 * * *',
    successRate: '99.4%',
    avgDuration: '18.6s',
    lastRun: 'vor 6 Std',
    activity24h: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'REONIC_API_KEY', value: '•••••••• (vault)' },
      { key: 'REONIC_BASE_URL', value: 'https://api.reonic.de/v3' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
      { key: 'SUPABASE_SERVICE_KEY', value: '•••••••• (vault)' },
    ],
    recentRuns: [
      { time: '03:00', duration: '17.8s', state: 'success', output: '42 Projekte · 18 Kontakte · 7 Angebote synced' },
      { time: '03:00', duration: '19.2s', state: 'success', output: '38 Projekte · 12 Kontakte · 5 Angebote synced' },
      { time: '03:00', duration: '16.4s', state: 'success', output: '41 Projekte · 15 Kontakte · 9 Angebote synced' },
      { time: '03:00', duration: '22.1s', state: 'warning', output: 'Reonic Rate-Limit 429 · Retry erfolgreich' },
      { time: '03:00', duration: '18.9s', state: 'success', output: '39 Projekte · 20 Kontakte · 4 Angebote synced' },
    ],
    logs: [
      { ts: '03:00:01.112', level: 'INFO', msg: 'Trigger fired · run_id=rs_7k2m1a' },
      { ts: '03:00:01.245', level: 'INFO', msg: 'Reonic API · GET /projects?updated_since=2026-06-06' },
      { ts: '03:00:04.812', level: 'INFO', msg: '→ 42 Projekte gefetcht' },
      { ts: '03:00:04.901', level: 'INFO', msg: 'Reonic API · GET /contacts?updated_since=2026-06-06' },
      { ts: '03:00:06.412', level: 'INFO', msg: '→ 18 Kontakte gefetcht' },
      { ts: '03:00:06.512', level: 'INFO', msg: 'Reonic API · GET /offers?updated_since=2026-06-06' },
      { ts: '03:00:08.112', level: 'INFO', msg: '→ 7 Angebote gefetcht' },
      { ts: '03:00:08.245', level: 'INFO', msg: 'Supabase upsert · projects (42 rows)' },
      { ts: '03:00:12.812', level: 'INFO', msg: 'Supabase upsert · contacts (18 rows)' },
      { ts: '03:00:16.412', level: 'INFO', msg: 'Supabase upsert · offers (7 rows)' },
      { ts: '03:00:18.912', level: 'SUCCESS', msg: 'Run complete · 67 records synced · 0 errors' },
    ],
  },
  {
    slug: 'netzanmeldungs-bot',
    name: 'Netzanmeldungs-Bot',
    cat: 'PRJ',
    desc: 'Automatische Portal-Anmeldungen bei Netzbetreibern (Sachsen Netze, MITNETZ, EnviaM u.a.) via Playwright',
    state: 'success',
    pill: 'LIVE',
    runs: '12',
    conns: 'Playwright · VPS 217.160.67.197',
    version: 'v3.4',
    schedule: 'Webhook · on demand',
    trigger: 'API-Aufruf / manuell',
    successRate: '94.2%',
    avgDuration: '48.3s',
    lastRun: 'vor 2 Std',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'VPS_HOST', value: '217.160.67.197:3099' },
      { key: 'PORTAL_CREDENTIALS', value: '•••••••• (vault)' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
      { key: 'DRIVER_COUNT', value: '50 Portal-Driver' },
      { key: 'HEADLESS', value: 'true' },
    ],
    recentRuns: [
      { time: '09:14', duration: '52.1s', state: 'success', output: 'MITNETZ · Anmeldung Projekt #P-4821 eingereicht' },
      { time: '08:47', duration: '44.8s', state: 'success', output: 'Sachsen Netze · Anmeldung Projekt #P-4819 eingereicht' },
      { time: '08:22', duration: '38.2s', state: 'success', output: 'MITNETZ · Anmeldung Projekt #P-4817 eingereicht' },
      { time: '07:58', duration: '62.4s', state: 'warning', output: 'EnviaM · Captcha-Retry · Anmeldung nach 2. Versuch OK' },
      { time: '07:31', duration: '41.6s', state: 'success', output: 'Sachsen Netze · Anmeldung Projekt #P-4815 eingereicht' },
    ],
    logs: [
      { ts: '09:14:01.012', level: 'INFO', msg: 'API trigger · project_id=P-4821 · netzbetreiber=MITNETZ' },
      { ts: '09:14:01.245', level: 'INFO', msg: 'Loading driver: mitnetz-strom-v2' },
      { ts: '09:14:02.812', level: 'INFO', msg: 'Playwright · launching headless browser' },
      { ts: '09:14:04.412', level: 'INFO', msg: 'Login MITNETZ Portal · installateurportal.mitnetz-strom.de' },
      { ts: '09:14:12.612', level: 'INFO', msg: 'Navigating to Netzanmeldung · Formular Step 1/4' },
      { ts: '09:14:28.812', level: 'INFO', msg: 'Filling PDF data · 18 Felder befüllt' },
      { ts: '09:14:42.112', level: 'INFO', msg: 'Upload: Lageplan + Schaltplan + Datenblatt' },
      { ts: '09:14:48.612', level: 'INFO', msg: 'Submit · Bestätigungsnummer: NA-2026-08412' },
      { ts: '09:14:52.112', level: 'SUCCESS', msg: 'Anmeldung eingereicht · Screenshot saved · Supabase updated' },
    ],
  },
  {
    slug: 'email-sync',
    name: 'Email-Sync',
    cat: 'KOM',
    desc: 'IMAP-Sync der Strato-Mailboxen (na@volta, info@volta) — ordnet E-Mails Projekten zu',
    state: 'success',
    pill: 'LIVE',
    runs: '96',
    conns: 'Strato IMAP · n8n Cloud',
    version: 'v1.5',
    schedule: 'Alle 15 Minuten',
    trigger: 'Cron · */15 * * * *',
    successRate: '99.8%',
    avgDuration: '3.4s',
    lastRun: 'vor 8 Min',
    activity24h: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
    envVars: [
      { key: 'IMAP_HOST', value: 'imap.strato.de' },
      { key: 'IMAP_USER_NA', value: 'na@volta-energietechnik.de' },
      { key: 'IMAP_USER_INFO', value: 'info@volta-energietechnik.de' },
      { key: 'IMAP_PASSWORD', value: '•••••••• (vault)' },
      { key: 'N8N_INSTANCE', value: 'voltasolaranlagen.app.n8n.cloud' },
    ],
    recentRuns: [
      { time: '10:45', duration: '3.2s', state: 'success', output: '4 neue E-Mails · 3 Projekten zugeordnet' },
      { time: '10:30', duration: '2.8s', state: 'success', output: '2 neue E-Mails · 2 Projekten zugeordnet' },
      { time: '10:15', duration: '3.1s', state: 'success', output: '6 neue E-Mails · 4 Projekten zugeordnet' },
      { time: '10:00', duration: '2.9s', state: 'success', output: '1 neue E-Mail · Projekt zugeordnet' },
      { time: '09:45', duration: '4.1s', state: 'warning', output: '8 E-Mails · 2 ohne Projekt-Match → Inbox' },
      { time: '09:30', duration: '3.0s', state: 'success', output: '3 neue E-Mails · 3 Projekten zugeordnet' },
    ],
    logs: [
      { ts: '10:45:01.112', level: 'INFO', msg: 'n8n trigger · workflow: Email-Sync-Volta' },
      { ts: '10:45:01.312', level: 'INFO', msg: 'IMAP connect · na@volta-energietechnik.de' },
      { ts: '10:45:01.812', level: 'INFO', msg: '→ 2 neue Nachrichten' },
      { ts: '10:45:02.012', level: 'INFO', msg: 'IMAP connect · info@volta-energietechnik.de' },
      { ts: '10:45:02.412', level: 'INFO', msg: '→ 2 neue Nachrichten' },
      { ts: '10:45:02.812', level: 'INFO', msg: 'Matching to projects via sender/subject' },
      { ts: '10:45:03.812', level: 'INFO', msg: 'Supabase · 4 emails stored · 3 project_ids matched' },
      { ts: '10:45:04.312', level: 'SUCCESS', msg: 'Run complete · 4 E-Mails processed' },
    ],
  },
  {
    slug: 'mahnbot',
    name: 'Mahnbot',
    cat: 'FIN',
    desc: 'Automatische Zahlungserinnerungen anhand sevDesk-Rechnungsstatus via n8n',
    state: 'success',
    pill: 'LIVE',
    runs: '4',
    conns: 'sevDesk · Strato SMTP · n8n',
    version: 'v2.1',
    schedule: 'Alle 6 Stunden',
    trigger: 'Cron · 0 */6 * * *',
    successRate: '99.2%',
    avgDuration: '5.8s',
    lastRun: 'vor 22 Min',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
    envVars: [
      { key: 'SEVDESK_API_KEY', value: '•••••••• (vault)' },
      { key: 'SMTP_HOST', value: 'smtp.strato.de' },
      { key: 'SMTP_USER', value: 'rechnung@volta-energietechnik.de' },
      { key: 'SMTP_PASSWORD', value: '•••••••• (vault)' },
      { key: 'MAHN_GEBUEHR_1', value: '€ 5' },
      { key: 'MAHN_GEBUEHR_2', value: '€ 15' },
      { key: 'N8N_INSTANCE', value: 'voltasolaranlagen.app.n8n.cloud' },
    ],
    recentRuns: [
      { time: '10:00', duration: '5.4s', state: 'success', output: '2 Erinnerungen versendet · 0 Fehler' },
      { time: '04:00', duration: '4.9s', state: 'success', output: '0 Erinnerungen · keine fälligen Posten' },
      { time: '22:00', duration: '6.1s', state: 'success', output: '1 Erinnerung versendet · 0 Fehler' },
      { time: '16:00', duration: '5.8s', state: 'success', output: '3 Erinnerungen versendet · 0 Fehler' },
      { time: '10:00', duration: '7.2s', state: 'warning', output: 'sevDesk Timeout · Retry erfolgreich' },
      { time: '04:00', duration: '5.1s', state: 'success', output: '0 Erinnerungen · keine fälligen Posten' },
    ],
    logs: [
      { ts: '10:00:01.231', level: 'INFO', msg: 'n8n trigger · workflow: Mahnbot-Volta' },
      { ts: '10:00:01.412', level: 'INFO', msg: 'sevDesk API · GET /Invoice?status=200&overdue=true' },
      { ts: '10:00:02.892', level: 'INFO', msg: '→ 8 offene Rechnungen gefetcht' },
      { ts: '10:00:02.945', level: 'INFO', msg: 'Filtering: fällig > 7 Tage' },
      { ts: '10:00:03.012', level: 'INFO', msg: '→ 2 Rechnungen fällig (Stufe 1)' },
      { ts: '10:00:03.245', level: 'INFO', msg: 'Rendering Mahnung-Templates · brand=volta' },
      { ts: '10:00:04.412', level: 'INFO', msg: 'Strato SMTP · sending 2 emails via rechnung@volta-energietechnik.de' },
      { ts: '10:00:05.812', level: 'INFO', msg: 'sevDesk PATCH · Mahnstatus aktualisiert' },
      { ts: '10:00:06.412', level: 'SUCCESS', msg: 'Run complete · 2 Mahnungen versendet · 0 errors' },
    ],
  },
  {
    slug: 'lieferbestaetigung',
    name: 'Lieferbestätigung',
    cat: 'PRJ',
    desc: 'Automatische Bestätigungsmails an Kunden bei Liefertermin-Updates aus Reonic',
    state: 'success',
    pill: 'LIVE',
    runs: '6',
    conns: 'Reonic · Strato SMTP · n8n',
    version: 'v1.2',
    schedule: 'Webhook',
    trigger: 'Reonic delivery_date_set',
    successRate: '100%',
    avgDuration: '2.8s',
    lastRun: 'vor 45 Min',
    activity24h: [0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'REONIC_WEBHOOK_SECRET', value: '•••••••• (vault)' },
      { key: 'SMTP_HOST', value: 'smtp.strato.de' },
      { key: 'SMTP_USER', value: 'info@volta-energietechnik.de' },
      { key: 'SMTP_PASSWORD', value: '•••••••• (vault)' },
      { key: 'N8N_INSTANCE', value: 'voltasolaranlagen.app.n8n.cloud' },
    ],
    recentRuns: [
      { time: '09:48', duration: '2.6s', state: 'success', output: 'Bestätigung an Fam. Krause · Lieferung 12.06.' },
      { time: '09:22', duration: '2.9s', state: 'success', output: 'Bestätigung an Hr. Müller · Lieferung 11.06.' },
      { time: '08:55', duration: '3.1s', state: 'success', output: 'Bestätigung an Fam. Weber · Lieferung 13.06.' },
      { time: '08:14', duration: '2.7s', state: 'success', output: 'Bestätigung an GmbH Baumann · Lieferung 10.06.' },
    ],
    logs: [
      { ts: '09:48:01.112', level: 'INFO', msg: 'n8n webhook · Reonic delivery_date_set · project=P-4832' },
      { ts: '09:48:01.345', level: 'INFO', msg: 'Loading customer data · Fam. Krause' },
      { ts: '09:48:01.812', level: 'INFO', msg: 'Rendering template: lieferbestaetigung_v2' },
      { ts: '09:48:02.412', level: 'INFO', msg: 'Strato SMTP · sending to krause@example.de' },
      { ts: '09:48:03.712', level: 'SUCCESS', msg: 'Bestätigung versendet · Liefertermin 12.06.2026' },
    ],
  },
  {
    slug: 'ki-dokumenten-filler',
    name: 'KI-Dokumenten-Filler',
    cat: 'PRJ',
    desc: 'Füllt Netzanmeldungs-PDFs automatisch per Claude Haiku AI — 100+ Templates, 25 Netzbetreiber',
    state: 'success',
    pill: 'LIVE',
    runs: '18',
    conns: 'Claude Haiku · Supabase · PDF-Engine',
    version: 'v2.8',
    schedule: 'On demand',
    trigger: 'API-Aufruf vom Netzanmeldungs-Bot',
    successRate: '97.8%',
    avgDuration: '6.2s',
    lastRun: 'vor 2 Std',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 3, 4, 5, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    envVars: [
      { key: 'ANTHROPIC_API_KEY', value: '•••••••• (vault)' },
      { key: 'AI_MODEL', value: 'claude-haiku' },
      { key: 'TEMPLATE_COUNT', value: '108' },
      { key: 'NETZBETREIBER_COUNT', value: '25' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
    ],
    recentRuns: [
      { time: '09:12', duration: '5.8s', state: 'success', output: 'PDF gefüllt · MITNETZ Anlagenanmeldung · 24 Felder' },
      { time: '08:48', duration: '6.4s', state: 'success', output: 'PDF gefüllt · Sachsen Netze EEG-Anmeldung · 31 Felder' },
      { time: '08:22', duration: '7.1s', state: 'warning', output: 'PDF gefüllt · 2 Felder unsicher (confidence < 80%)' },
      { time: '07:58', duration: '5.9s', state: 'success', output: 'PDF gefüllt · EnviaM Inbetriebsetzung · 19 Felder' },
      { time: '07:31', duration: '6.2s', state: 'success', output: 'PDF gefüllt · Sachsen Netze Anlagenanmeldung · 28 Felder' },
    ],
    logs: [
      { ts: '09:12:01.012', level: 'INFO', msg: 'API call · fill_pdf · template=mitnetz_anlagenanmeldung_v3' },
      { ts: '09:12:01.245', level: 'INFO', msg: 'Loading project data · P-4821 from Supabase' },
      { ts: '09:12:01.812', level: 'INFO', msg: 'Claude Haiku · extracting field values from project context' },
      { ts: '09:12:04.012', level: 'INFO', msg: '→ 24/24 Felder mapped · confidence avg 94%' },
      { ts: '09:12:04.412', level: 'INFO', msg: 'PDF-Engine · filling template · mitnetz_anlagenanmeldung_v3.pdf' },
      { ts: '09:12:06.012', level: 'INFO', msg: 'Supabase storage · upload filled PDF' },
      { ts: '09:12:06.812', level: 'SUCCESS', msg: 'PDF complete · 24 Felder · 0 warnings' },
    ],
  },
  {
    slug: 'enrichment-bot',
    name: 'Enrichment-Bot',
    cat: 'CRM',
    desc: 'Extrahiert technische Daten aus Reonic-Dokumenten (kWp, WR-Typ, Speicher) per AI',
    state: 'success',
    pill: 'LIVE',
    runs: '34',
    conns: 'Claude Haiku · Reonic · Supabase',
    version: 'v1.6',
    schedule: 'Alle 2 Stunden',
    trigger: 'Cron · 0 */2 * * *',
    successRate: '96.4%',
    avgDuration: '12.4s',
    lastRun: 'vor 38 Min',
    activity24h: [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    envVars: [
      { key: 'ANTHROPIC_API_KEY', value: '•••••••• (vault)' },
      { key: 'AI_MODEL', value: 'claude-haiku' },
      { key: 'REONIC_API_KEY', value: '•••••••• (vault)' },
      { key: 'SUPABASE_URL', value: '•••••••• (vault)' },
      { key: 'EXTRACT_FIELDS', value: 'kwp,wr_type,speicher_kwh,module_count' },
    ],
    recentRuns: [
      { time: '10:00', duration: '11.8s', state: 'success', output: '5 Dokumente enriched · 18 Felder extrahiert' },
      { time: '08:00', duration: '14.2s', state: 'success', output: '8 Dokumente enriched · 29 Felder extrahiert' },
      { time: '06:00', duration: '9.8s', state: 'success', output: '3 Dokumente enriched · 11 Felder extrahiert' },
      { time: '04:00', duration: '12.1s', state: 'warning', output: '6 Dokumente · 1 PDF nicht lesbar (Scan-Qualität)' },
      { time: '02:00', duration: '13.4s', state: 'success', output: '7 Dokumente enriched · 24 Felder extrahiert' },
    ],
    logs: [
      { ts: '10:00:01.112', level: 'INFO', msg: 'Trigger fired · run_id=eb_3f8k2c' },
      { ts: '10:00:01.345', level: 'INFO', msg: 'Reonic API · fetching unprocessed documents' },
      { ts: '10:00:02.812', level: 'INFO', msg: '→ 5 neue Dokumente seit letztem Run' },
      { ts: '10:00:03.012', level: 'INFO', msg: 'Claude Haiku · extracting: kWp, WR-Typ, Speicher, Modulanzahl' },
      { ts: '10:00:08.412', level: 'INFO', msg: '→ Doc 1: 9.8 kWp · Fronius GEN24 · BYD HVS 10.2 · 24 Module' },
      { ts: '10:00:09.812', level: 'INFO', msg: '→ Doc 2: 12.4 kWp · SMA STP · keine Batterie · 31 Module' },
      { ts: '10:00:11.012', level: 'INFO', msg: 'Supabase · updating project_technical_data (5 rows)' },
      { ts: '10:00:12.912', level: 'SUCCESS', msg: 'Run complete · 5 docs · 18 fields extracted · 0 errors' },
    ],
  },
  {
    slug: 'ecoflow-connector',
    name: 'EcoFlow-Connector',
    cat: 'IOT',
    desc: 'Monitoring der Kundenanlagen via EcoFlow IoT API — Geräte müssen noch verknüpft werden',
    state: 'neutral',
    pill: 'EINRICHTUNG',
    runs: '—',
    conns: 'EcoFlow IoT API · Supabase',
    version: 'v0.3',
    schedule: 'Alle 5 Minuten (geplant)',
    trigger: 'Cron · */5 * * * * (inaktiv)',
    successRate: '—',
    avgDuration: '—',
    lastRun: 'noch nie',
    activity24h: Array(24).fill(0),
    envVars: [
      { key: 'ECOFLOW_ACCESS_KEY', value: '•••••••• (vault)' },
      { key: 'ECOFLOW_SECRET_KEY', value: '•••••••• (vault)' },
      { key: 'ECOFLOW_API_URL', value: 'https://api.ecoflow.com/iot-open' },
      { key: 'DEVICES_LINKED', value: '0 / 12 geplant' },
    ],
    recentRuns: [],
    logs: [
      { ts: '—', level: 'WARN', msg: 'Bot wartet auf Geräte-Verknüpfung · EcoFlow-Kundengeräte müssen im Portal verlinkt werden' },
      { ts: '—', level: 'INFO', msg: 'API-Zugang getestet · Auth OK · 0 devices linked' },
    ],
  },
];

export function getVoltaBot(slug: string): Bot | undefined {
  return voltaBots.find((b) => b.slug === slug);
}
